// Code generated by "enumer -type=ShellType -trimprefix=ShellType -transform=kebab"; DO NOT EDIT.

package bind

import (
	"fmt"
	"strings"
)

const _ShellTypeName = "autoshpowershellcmd"

var _ShellTypeIndex = [...]uint8{0, 4, 6, 16, 19}

const _ShellTypeLowerName = "autoshpowershellcmd"

func (i ShellType) String() string {
	if i < 0 || i >= ShellType(len(_ShellTypeIndex)-1) {
		return fmt.Sprintf("ShellType(%d)", i)
	}
	return _ShellTypeName[_ShellTypeIndex[i]:_ShellTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ShellTypeNoOp() {
	var x [1]struct{}
	_ = x[ShellTypeAuto-(0)]
	_ = x[ShellTypeSh-(1)]
	_ = x[ShellTypePowershell-(2)]
	_ = x[ShellTypeCmd-(3)]
}

var _ShellTypeValues = []ShellType{ShellTypeAuto, ShellTypeSh, ShellTypePowershell, ShellTypeCmd}

var _ShellTypeNameToValueMap = map[string]ShellType{
	_ShellTypeName[0:4]:        ShellTypeAuto,
	_ShellTypeLowerName[0:4]:   ShellTypeAuto,
	_ShellTypeName[4:6]:        ShellTypeSh,
	_ShellTypeLowerName[4:6]:   ShellTypeSh,
	_ShellTypeName[6:16]:       ShellTypePowershell,
	_ShellTypeLowerName[6:16]:  ShellTypePowershell,
	_ShellTypeName[16:19]:      ShellTypeCmd,
	_ShellTypeLowerName[16:19]: ShellTypeCmd,
}

var _ShellTypeNames = []string{
	_ShellTypeName[0:4],
	_ShellTypeName[4:6],
	_ShellTypeName[6:16],
	_ShellTypeName[16:19],
}

// ShellTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ShellTypeString(s string) (ShellType, error) {
	if val, ok := _ShellTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ShellTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ShellType values", s)
}

// ShellTypeValues returns all values of the enum
func ShellTypeValues() []ShellType {
	return _ShellTypeValues
}

// ShellTypeStrings returns a slice of all String values of the enum
func ShellTypeStrings() []string {
	strs := make([]string, len(_ShellTypeNames))
	copy(strs, _ShellTypeNames)
	return strs
}

// IsAShellType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ShellType) IsAShellType() bool {
	for _, v := range _ShellTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
